### ISSUE TITLE
Move Pocket Core Dockerfile and entrypoint/cmd scripts to this repo

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core-deployments#14]
Currently, all Docker image files are being hosted in the Pocket Core repo. With this new repo we want to keep all the deployment artifacts in one place.

Implementation:

1. Create a root folder named `docker` in this repo.
2. Move the Dockerfile and scripts from the `pocket-core` repo to here.
3. Change the Docker Cloud config to point to this Repo.

**Comment by nelcolon** [comment]
Closed with PR: https://github.com/pokt-network/pocket-core-deployments/pull/20
