### ISSUE TITLE
RC-0.6.0 upgrade issues general

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core-deployments#184]
Needed a place to start tracking all of this stuff:  We definitely have some issues, but gonna need to get samples and pictures and numbers to see if I can trace down any common causes.

#1.  Call it the "Evidence issue".  successfully converted nodes catch an error and die hours (up to 24 hours) after upgrade so far.
The error message is: 
 
 can't unmarshal GOBEvidence iterator value into GOBEvidence: could not unmarshal into ProtoEvidence from cache, moduleCdc unmarshal binary bare: proto: wrong wireType = 0 for field Proofs
 
I think there is a different GOBEvidence error also, I will try to catch it.

sometimes deleting pocket_evidence.db and restarting the client will fix it, most times data corruption has occured and a bootstrap from another node is required.

#2.  100 nodes upgraded so far.   Instant success rate: 19/20.   4 hour success rate: 15/20  12 hour success rate: 12/20.
Pausing the upgrade process because of the errors which result in corruption.  I can't constantly reload these things.

**Comment by BenVanGithub** [comment]
Node: sm77

2021/04/03 18:53:16 can't unmarshal GOBEvidence iterator value into GOBEvidence: could not unmarshal into ProtoEvidence from cache, moduleCdc unmarshal binary bare: proto: ProtoEvidence: wiretype end group for non-group

Action:  delete evidence DB, Pocket start
Result:  success (so far)

**Comment by BenVanGithub** [comment]
Node: sm92

2021/04/03 18:52:54 can't unmarshal GOBEvidence iterator value into GOBEvidence: could not unmarshal into ProtoEvidence from cache, moduleCdc unmarshal binary bare: proto: wrong wireType = 1 for field BloomBytes

Action: delete evidence DB, Pocket start
Result: success (so far)

**Comment by BenVanGithub** [comment]
Another batch of 25:
100% start fine
8% (2 nodes) die within 4 or 5 blocks.  corrupted data . bootstrap and restart
12% (3 nodes) die in the 8 to 12 block range.  1 corrupted data, 2 restarted OK after delete pocket_evidence .
All dead node show some type of error like:

2021/04/04 00:06:11 can't unmarshal GOBEvidence iterator value into GOBEvidence: could not unmarshal into ProtoEvidence from cache, moduleCdc unmarshal binary bare: proto: ProtoEvidence: illegal tag 0 (wire type 0)

**Comment by BenVanGithub** [comment]
Nodes seem to stabilize after about 3 or 4 hours.

**Comment by BenVanGithub** [comment]
OK.  Here is what I know after 200 upgrades.
1.)  100% of nodes with outstanding claims will die with the "evidence error" within a few hours of being upgraded.
2.)  10% of nodes with no outstanding claims will die with the "evidence error" within a few hours of being upgraded.
3.)   0% of nodes who's pocket_evidence.db has been removed will die from the GOBEvidence error.

That should close the book on where the problem is.

**Comment by andrewnguyen22** [comment]
Thanks @BenVanGithub, the release notes *should have* said to delete the evidence db. I think they were updated over the past weekend

**Comment by andrewnguyen22** [comment]
@BenVanGithub you pointed out a great flaw in the upgrade logic that I'm trying to amend here:
https://github.com/pokt-network/pocket-core/issues/1274

The deletion of the evidence db isn't the best solution. keep an eye on this issue above for a more elegant (no money lost) solution

**Comment by andrewnguyen22** [comment]
Closed with RC-0.6.1
