### ISSUE TITLE
Prometheus fail to start

### ISSUE THREAD

**Issue by jorgecuesta** [pokt-network/pocket-core-deployments#189]
Guys here you can check this, depends on the user that is running docker in server who user in prometheus should be.
https://github.com/prometheus/prometheus/issues/5976#issuecomment-540457847

In theory 1000 should work but not always, in my case I change it to root, no mater than I have a different user that has sudo permissions.
https://github.com/pokt-network/pocket-core-deployments/blob/28ff232093d25c3ba5bd7f345f7fa6c8636bc2f9/docker-compose/stacks/pocket-validator/docker-compose.yaml#L80

**Comment by aqt01** [comment]
Yes, this was solved here 
https://github.com/pokt-network/pocket-core-deployments/pull/170

You need to run first
`sudo bash install.sh`

As described in per the documentation
https://github.com/pokt-network/pocket-core-deployments/tree/staging/docker-compose/stacks/pocket-validator#installing-loki-driver-plugin-and-set-grafanaprometheus-permissions
